server:
  port: 3001

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ash_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: password
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: ash-ware
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml